language: node_js
node_js:
  - "4.1"
services:
  - docker
before_install:
  - docker pull mongo
  - docker run -d -p 27017:27017 mongo
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
