version: '2'
services:
  analogist:
    image: node:8.11.1-wheezy
    volumes:
      - .:/app
    working_dir: /app
    links:
      - analogistdb:mongodb
      - opbadge
    ports:
      - "3000:3000"
    environment:
      - ANG_TRELLO_KEY
      - ANG_TRELLO_SECRET
      - ANG_TRELLO_BOARDID
      - ANG_MONGO_HOST=mongodb
      - ANG_BADGE_ANALYSES_BRONZE
      - ANG_BADGE_ANALYSES_SILVER
      - http_proxy
      - https_proxy
      - no_proxy
    tty: true
    command: npm run dev

  analogistdb:
    image: mongo:3.4.4
    volumes:
      - ./data/db:/data/db
    command: --smallfiles

  opbadge:
    image: ezpaarseproject/ezpaarse-badge
    environment:
      - http_proxy
      - https_proxy
      - OBF_CERT
    volumes:
      - ./ssl:/usr/src/app/app/ssl
    ports:
      - "4000:4000"
    links:
      - analogistdb:mongodb
