version: '2'
services:
  analogist:
    image: node:8.11.1-wheezy
    volumes:
      - .:/app
    working_dir: /app
    links:
      - analogistdb:mongodb
    ports:
      - "3000:3000"
    environment:
      - ANG_TRELLO_KEY
      - ANG_TRELLO_SECRET
      - ANG_TRELLO_BOARDID
      - ANG_MONGO_HOST=mongodb
      - http_proxy
      - https_proxy
      - no_proxy
    tty: true
    command: npm run dev

  analogistdb:
    image: mongo:3.6.5
    volumes:
      - ./data/db:/data/db
    command: --smallfiles
