version: '3'
services:
  analogist:
    image: node:8.11.1-wheezy
    volumes:
      - .:/app
      - ./uploads:/usr/src/app/app/uploads
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - ANG_TRELLO_KEY
      - ANG_TRELLO_SECRET
      - ANG_TRELLO_BOARDID
      - ANG_MONGO_HOST=db
      - ANG_BADGE_HOST=opbadge
      - ANG_BADGE_ANALYSES_BRONZE_ID
      - ANG_BADGE_ANALYSES_BRONZE_NAME
      - ANG_BADGE_ANALYSES_BRONZE_EVENT
      - ANG_BADGE_ANALYSES_SILVER_ID
      - ANG_BADGE_ANALYSES_SILVER_NAME
      - ANG_BADGE_ANALYSES_SILVER_EVENT
      - ANG_BADGE_ISSUER
      - ANG_SMTP_HOST
      - ANG_SMTP_PORT
      - ANG_NOTIFICATIONS_SENDER
      - ANG_NOTIFICATIONS_RECEIVERS
      - http_proxy
      - https_proxy
      - no_proxy=localhost,127.0.0.1,opbadge
      - NODE_CONFIG
    tty: true
    command: npm run dev

  db:
    image: mongo:3.6.5
    volumes:
      - ./data/db:/data/db
    command: --smallfiles

  opbadge:
    image: ezpaarseproject/ezpaarse-badge:1.1.12
    environment:
      - http_proxy
      - https_proxy
      - OBF_CERT
      - BADGE_MONGO_HOST=db
      - BADGE_MONGO_PORT
      - BADGE_MONGO_DB
      - BADGE_LOGENTRY_CLIENT
      - BADGE_LOGENTRY_ISSUER
      - BADGE_AUTHORITY
    volumes:
      - ./ssl:/usr/src/app/app/ssl
    ports:
      - "4000:4000"

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
