version: '2'
services:
  front:
    build: 
      context: ./front
      args:
        - http_proxy
        - https_proxy
    ports:
      - 8080:8080
    environment:
      - API_URL=http://${ANALOGIST_DOMAIN}/api
      - PORT=8080
      - HOST=0.0.0.0
    restart: unless-stopped

  api:
    build:
      context: ./api
      args:
        - http_proxy
        - https_proxy
    ports:
      - 3000:3000
    environment:
      # les variables d'environnement pour l'accès au board trello par l'application
      # exemple le board de prod : https://trello.com/b/wEaLnz8d/ezpaarse-analogist-suivi-des-plateformes
      - ANG_TRELLO_KEY
      - ANG_TRELLO_SECRET
      - ANG_TRELLO_BOARDID
      - ANG_MONGO_HOST=mongo
      # les variables d'envrionnement pour les badges
      - ANG_BADGE_HOST=opbadge
      - ANG_BADGE_ANALYSES_BRONZE_ID
      - ANG_BADGE_ANALYSES_BRONZE_NAME
      - ANG_BADGE_ANALYSES_BRONZE_EVENT
      - ANG_BADGE_ANALYSES_SILVER_ID
      - ANG_BADGE_ANALYSES_SILVER_NAME
      - ANG_BADGE_ANALYSES_SILVER_EVENT
      - ANG_BADGE_ISSUER
      # les variables d'environnement pour les mails
      - ANG_SMTP_HOST
      - ANG_SMTP_PORT
      - ANG_NOTIFICATIONS_SENDER
      - ANG_NOTIFICATIONS_RECEIVERS
      # les variables d'environnement pour que l'application puisse accéder à l'exterieur (ex: l'API trello)
      - http_proxy
      - https_proxy
      - no_proxy=localhost,127.0.0.1,opbadge
      - NODE_CONFIG
      - HTTPS_PROTOCOL
    volumes:
      - ./api/uploads:/usr/src/app/app/uploads
    tty: true
    restart: on-failure

  opbadge:
    image: ezpaarseproject/ezpaarse-badge:1.1.14
    environment:
      - http_proxy
      - https_proxy
      - OBF_CERT
      - BADGE_MONGO_HOST=mongo
      - BADGE_MONGO_PORT
      - BADGE_MONGO_DB
      - BADGE_LOGENTRY_CLIENT
      - BADGE_LOGENTRY_ISSUER
      - BADGE_AUTHORITY
    volumes:
      - ./ssl:/usr/src/app/app/ssl
    restart: on-failure

  rp:
    build: 
      context: ./rp
      args: 
        - ANALOGIST_DOMAIN
    ports:
      - 80:80
      - 443:443
    environment:
      - http_proxy
      - https_proxy
      - ANALOGIST_DOMAIN
    volumes:
      - ./logs/:/etc/nginx/logs/
    restart: unless-stopped

  mongo:
    image: mongo:3.6.5
    volumes:
      - ./data/db:/data/db
    command: --smallfiles
    restart: on-failure