version: '2'
services:
  analogist:
    image: node:8.11.1-wheezy
    volumes:
      - .:/app
    working_dir: /app
    links:
      - analogistdb:mongodb
      - opbadge
      - maildev
    ports:
      - "3000:3000"
    environment:
      - ANG_TRELLO_KEY=1fbb22dbae7df154e220b517a4f4acac
      - ANG_TRELLO_SECRET=f58ea5fb38bce1d8257af61352a35efe2788b2b8fb6e353b89f609cd512b426f
      - ANG_TRELLO_BOARDID=58fdab8b19266cf7cd79c1c6
      - ANG_MONGO_HOST=mongodb
      - ANG_BADGE_ANALYSES_BRONZE_ID=PB0V36aFMQaVX
      - ANG_BADGE_ANALYSES_BRONZE_NAME='Analyse bronze'
      - ANG_BADGE_ANALYSES_BRONZE_EVENT=analyse
      - ANG_BADGE_ANALYSES_SILVER_ID=PB0VFWaFMQaW4
      - ANG_BADGE_ANALYSES_SILVER_NAME='Analyse argent'
      - ANG_BADGE_ANALYSES_SILVER_EVENT=analyse
      - ANG_NOTIFICATIONS_SENDER='AnalogIST <analogist@inist.fr>'
      - ANG_NOTIFICATIONS_RECEIVERS='dominique.lechaudel@gmail.com,frederic.truong@inist.fr,sylvie.franck@inist.fr,yannick.schurter@inist.fr,stephane.gully@inist.fr,steven.wilmouth@inist.fr'
      - ANG_SMTP_HOST=maildev
      - ANG_SMTP_PORT=25
      - http_proxy=http://proxyout.inist.fr:8080
      - https_proxy=http://proxyout.inist.fr:8080
      - no_proxy=localhost,127.0.0.1,opbadge,maildev
    tty: true
    command: npm run dev

  analogistdb:
    image: mongo:3.6.5
    volumes:
      - ./data/db:/data/db
    command: --smallfiles

  opbadge:
    image: ezpaarseproject/ezpaarse-badge
    environment:
      - http_proxy=http://proxyout.inist.fr:8080
      - https_proxy=http://proxyout.inist.fr:8080
      - OBF_CERT=thDJqDKuOgBpABJHlGH764Huh0h5YMaHiV9qUgO9MGIuMsvwCng03ENdxdQQpkMOWS2zNIjgIPbqxh/WdqYMrerTaq6mFaaowe6kv54/9vzYm53BijDU8hn5x3x99TTzlexfR5KUZMEZVUyBANGxdhZTRjrbmcIDuj5wDpwu6iKQ9uS1kog6AkgxhwO0+4yksg/BNtmyejyCdAhXMGG7jii4tr25IX3bdbVH/5DoP/bZzSmtzWsSpCxBq5rkMtbx10v8wVyGxY1hPd11PQC7f47y88O56R3WexqQiDf7FR++OxjyM4PCIAiDbaYzJ/KTNfkhsmI1SxTHMd7ksdqYuw==
      - BADGE_MONGO_HOST=mongodb
      - BADGE_MONGO_PORT
      - BADGE_MONGO_DB
      - BADGE_LOGENTRY_CLIENT=ezpaarse-badge
      - BADGE_LOGENTRY_ISSUER=AnalogIST
    volumes:
      - ./ssl:/usr/src/app/app/ssl
    ports:
      - "4000:4000"
    links:
      - analogistdb:mongodb

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
