version: '2'
services:
  front:
    image: node:14.15.0
    volumes:
      - ./front:/usr/src/front
    working_dir: /usr/src/front
    ports:
      - 8080:8080
    environment:
      - API_URL=https://${ANALOGIST_DOMAIN}/api
      - PORT=8080
      - HOST=0.0.0.0
    command: npm run dev
    restart: "on-failure"

  api:
    image: node:14.15.0
    volumes:
      - ./api:/usr/src/api
    working_dir: /usr/src/api
    ports:
      - 3000:3000
    environment:
      # les variables d'environnement pour l'accès au board trello par l'application
      # exemple le board de prod : https://trello.com/b/wEaLnz8d/ezpaarse-analogist-suivi-des-plateformes
      - ANG_TRELLO_KEY
      - ANG_TRELLO_SECRET
      - ANG_TRELLO_BOARDID
      - ANG_MONGO_HOST=mongo
      # les variables d'envrionnement pour les badges
      - ANG_BADGE_HOST=opbadge
      - ANG_BADGE_ANALYSES_BRONZE_ID
      - ANG_BADGE_ANALYSES_BRONZE_NAME
      - ANG_BADGE_ANALYSES_BRONZE_EVENT
      - ANG_BADGE_ANALYSES_SILVER_ID
      - ANG_BADGE_ANALYSES_SILVER_NAME
      - ANG_BADGE_ANALYSES_SILVER_EVENT
      - ANG_BADGE_ISSUER
      # les variables d'environnement pour les mails
      - ANG_SMTP_HOST
      - ANG_SMTP_PORT
      - ANG_NOTIFICATIONS_SENDER
      - ANG_NOTIFICATIONS_RECEIVERS
      # les variables d'environnement pour que l'application puisse accéder à l'exterieur (ex: l'API trello)
      - http_proxy
      - https_proxy
      - no_proxy=localhost,127.0.0.1,opbadge
      - ANG_EZPAARSE_URL
      - NODE_CONFIG
    command: npm run dev
    restart: "on-failure"

  opbadge:
    image: ezpaarseproject/ezpaarse-badge:1.1.14
    ports:
      - 4000:4000
    environment:
      - http_proxy
      - https_proxy
      - OBF_CERT
      - BADGE_MONGO_HOST=mongo
      - BADGE_MONGO_PORT
      - BADGE_MONGO_DB
      - BADGE_LOGENTRY_CLIENT
      - BADGE_LOGENTRY_ISSUER
      - BADGE_AUTHORITY
    volumes:
      - ./ssl:/usr/src/app/app/ssl
    restart: on-failure

  doc:
    image: node:14.15.0
    volumes:
      - ./docs:/usr/src/docs
    working_dir: /usr/src/docs
    ports:
      - 45410:45410
    environment:
      - PORT=45410
      - HOST=0.0.0.0
    command: npm run dev
    restart: "on-failure"

  rp:
    extends:
      file: docker-compose.yml
      service: rp

  mongo:
    extends:
      file: docker-compose.yml
      service: mongo

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80