version: '3'
services:
  analogist:
    image: node:18.12.0-alpine3.16
    volumes:
      - .:/app
      - ./uploads:/usr/src/app/app/uploads
    working_dir: /app
    ports:
      - 80:3000
    environment:
      - ANG_TRELLO_KEY
      - ANG_TRELLO_SECRET
      - ANG_TRELLO_TOKEN
      - ANG_TRELLO_BOARDID
      - ANG_MONGO_HOST=db
      - ANG_SMTP_HOST=maildev
      - ANG_SMTP_PORT=25
      - ANG_NOTIFICATIONS_SENDER
      - ANG_NOTIFICATIONS_RECEIVERS
      - NODE_CONFIG
    tty: true
    command: npm run dev

  db:
    image: mongo:3.6.5
    volumes:
      - ./data/db:/data/db
    command: --smallfiles

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
