version: '3'

services:
  opbadge:
    image: ezpaarseproject/ezpaarse-badge:1.1.14
    environment:
      - http_proxy
      - https_proxy
      - OBF_CERT
    volumes:
      - ./ssl:/usr/src/app/app/ssl
    command: npm run conf
